### ISSUE TITLE
Detuned

### ISSUE THREAD

**Issue by velolala** [Marzac/zekit#1]
Hi!
I just received my pre assembled Zekit. While playing with it, I noticed, that all Midi Notes that I play are exactly 50cent too low. Any idea what is going on here?

**Comment by Marzac** [comment]
Hi velolala.

thank you for your message.

For these non-software related issues, please prefer using the support system
from Fred's Lab instead : https://support.fredslab.net
or drop us a post on modwiggler Zekit related forum.

To answer your question:

ZeKit master tuning can be adjusted, here is the procedure.
1 - Go to the MIDI page (press WAVE and MOTIFS together)
2 - Send MIDI modwheel messages (using a keyboard or a MIDI software tool)
     to adjust the master fine tuning. You will be able to correct the drift that way.
3 - Exit the MIDI page (any page button) to store the setting.

Best greetings, Frédéric

**Comment by velolala** [comment]
Thanks Frédéric!
Since it was such an exact 50cent, I was assuming some software issue, i.e. an off-by-one somewhere in the pitch selection. But it is great to hear there is a master tune available :)

Luckily by reading through the code I already figured out the MIDI page. Btw: are there any other hidden menu functions, and where could I read about them?

Feel free to close this issue!
